{
    "create": {
        "database": {
            "name": "CreditCollections",
            "compatibilityLevel": 1400,
            "model": {
                "culture": "en-US",
                "dataSources": [
                    {
                        "type": "structured",
                        "name": "dataLakeStore",
                        "connectionDetails": {
                            "protocol": "data-lake-store",
                            "address": {
                                "url": "https://cdsamock.azuredatalakestore.net"
                            }
                        },
                        "credential": {
                            "AuthenticationKind": "OAuth2",
                            "kind": "DataLake",
                            "path": "https://cdsamock.azuredatalakestore.net/",
                            "Expires": null,
                            "RefreshToken": "********",
                            "token_type": "********",
                            "scope": "********",
                            "ext_expires_in": "********",
                            "expires_on": "********",
                            "not_before": "********",
                            "resource": "********",
                            "id_token": "********"
                        }
                    }
                ],
                "tables": [
                    {
                        "name": "Customer dimension",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "COMPANY",
                                "dataType": "string",
                                "sourceColumn": "COMPANY"
                            },
                            {
                                "name": "BLOCKED_VALUE",
                                "dataType": "int64",
                                "sourceColumn": "BLOCKED_VALUE"
                            },
                            {
                                "name": "COUNTY",
                                "dataType": "string",
                                "sourceColumn": "COUNTY"
                            },
                            {
                                "name": "STATE",
                                "dataType": "string",
                                "sourceColumn": "STATE"
                            },
                            {
                                "name": "CITY",
                                "dataType": "string",
                                "sourceColumn": "CITY"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "ROW_UNIQUEKEY",
                                "dataType": "int64",
                                "sourceColumn": "ROW_UNIQUEKEY"
                            },
                            {
                                "name": "BLOCKED",
                                "dataType": "string",
                                "sourceColumn": "BLOCKED"
                            },
                            {
                                "name": "Customer account",
                                "dataType": "string",
                                "sourceColumn": "Customer account"
                            },
                            {
                                "name": "Customer group",
                                "dataType": "string",
                                "sourceColumn": "Customer group"
                            },
                            {
                                "name": "Credit rating",
                                "dataType": "string",
                                "sourceColumn": "Credit rating"
                            },
                            {
                                "name": "Country/Region",
                                "dataType": "string",
                                "sourceColumn": "Country/Region"
                            },
                            {
                                "name": "District",
                                "dataType": "string",
                                "sourceColumn": "District"
                            },
                            {
                                "name": "Zip/Postal code",
                                "dataType": "string",
                                "sourceColumn": "Zip/Postal code"
                            },
                            {
                                "name": "Company1",
                                "dataType": "string",
                                "sourceColumn": "Company1"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustTable = Source{[Name=\"CustCollectionsBIMeasurements_CustTable\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustTable1 = CustCollectionsBIMeasurements_CustTable{[Name=\"CustCollectionsBIMeasurements_CustTable\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustTable1,[Delimiter=\",\", Columns=17, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"ACCOUNTNUM\", type text}, {\"COMPANY\", type text}, {\"CUSTGROUP\", type text}, {\"CREDITRATING\", type text}, {\"BLOCKED_VALUE\", Int64.Type}, {\"GEOGRAPHICLOCATION\", type text}, {\"COUNTY\", type text}, {\"STATE\", type text}, {\"CITY\", type text}, {\"DISTRICTNAME\", type text}, {\"ZIPCODE\", type text}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"ROW_UNIQUEKEY\", Int64.Type}, {\"BLOCKED\", type text}}),",
                                        "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"ACCOUNTNUM\", \"Customer account\"}, {\"BLOCKED\", \"Blocked\"}, {\"CITY\", \"City\"}, {\"COMPANY\", \"Company\"}, {\"COUNTY\", \"County\"}, {\"CREDITRATING\", \"Credit rating\"}, {\"CUSTGROUP\", \"Customer group\"}, {\"DISTRICTNAME\", \"District\"}, {\"STATE\", \"State\"}, {\"ZIPCODE\", \"Zip/Postal code\"}, {\"DATAAREAID\", \"Company1\"}, {\"GEOGRAPHICLOCATION\", \"Country/Region\"}})",
                                        "in",
                                        "    #\"Renamed Columns\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Activities average days to close",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "CustCollectionsBIMeasurements_CustTable_FK",
                                "dataType": "int64",
                                "sourceColumn": "CustCollectionsBIMeasurements_CustTable_FK"
                            },
                            {
                                "name": "Days to close an activity",
                                "dataType": "int64",
                                "sourceColumn": "Days to close an activity"
                            },
                            {
                                "name": "Activity number",
                                "dataType": "int64",
                                "sourceColumn": "Activity number"
                            },
                            {
                                "name": "Company",
                                "dataType": "string",
                                "sourceColumn": "Company"
                            },
                            {
                                "name": "Customer account",
                                "dataType": "string",
                                "sourceColumn": "Customer account"
                            },
                            {
                                "name": "Customer name",
                                "dataType": "string",
                                "sourceColumn": "Customer name"
                            },
                            {
                                "name": "Responsible worker",
                                "dataType": "string",
                                "sourceColumn": "Responsible worker"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIActivitiesAverageCloseTime = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIActivitiesAverageCloseTime\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIActivitiesAverageCloseTime1 = CustCollectionsBIMeasurements_CustCollectionsBIActivitiesAverageCloseTime{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIActivitiesAverageCloseTime\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBIActivitiesAverageCloseTime1,[Delimiter=\",\", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"AVERAGECLOSEDTIME\", Int64.Type}, {\"NUMOFACTIVITIES\", Int64.Type}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"ACCOUNTNUM\", type text}, {\"CUSTOMERNAME\", type text}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}, {\"RESPONSIBLEWORKER\", type text}}),",
                                        "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"ACCOUNTNUM\", \"Customer account\"}, {\"AVERAGECLOSEDTIME\", \"Days to close an activity\"}, {\"DATAAREAID\", \"Company\"}, {\"CUSTOMERNAME\", \"Customer name\"}, {\"RESPONSIBLEWORKER\", \"Responsible worker\"}, {\"NUMOFACTIVITIES\", \"Activity number\"}})",
                                        "in",
                                        "    #\"Renamed Columns\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Customers on hold",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "SALESID",
                                "dataType": "int64",
                                "sourceColumn": "SALESID"
                            },
                            {
                                "name": "DATAAREAID",
                                "dataType": "string",
                                "sourceColumn": "DATAAREAID"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "CUSTACCOUNT",
                                "dataType": "string",
                                "sourceColumn": "CUSTACCOUNT"
                            },
                            {
                                "name": "SALESNAME",
                                "dataType": "string",
                                "sourceColumn": "SALESNAME"
                            },
                            {
                                "name": "MCRREASONCODE",
                                "dataType": "string",
                                "sourceColumn": "MCRREASONCODE"
                            },
                            {
                                "name": "CustCollectionsBIMeasurements_CustTable_FK",
                                "dataType": "int64",
                                "sourceColumn": "CustCollectionsBIMeasurements_CustTable_FK"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBISalesOnHold = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBISalesOnHold\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBISalesOnHold1 = CustCollectionsBIMeasurements_CustCollectionsBISalesOnHold{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBISalesOnHold\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBISalesOnHold1,[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"SALESID\", Int64.Type}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"CUSTACCOUNT\", type text}, {\"SALESNAME\", type text}, {\"MCRREASONCODE\", type text}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}})",
                                        "in",
                                        "    #\"Changed Type\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Sales on hold",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "string",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "CustCollectionsBIMeasurements_CustTable_FK",
                                "dataType": "string",
                                "sourceColumn": "CustCollectionsBIMeasurements_CustTable_FK"
                            },
                            {
                                "name": "Sales ID",
                                "dataType": "string",
                                "sourceColumn": "Sales ID"
                            },
                            {
                                "name": "Company",
                                "dataType": "string",
                                "sourceColumn": "Company"
                            },
                            {
                                "name": "Customer account",
                                "dataType": "string",
                                "sourceColumn": "Customer account"
                            },
                            {
                                "name": "Customer name",
                                "dataType": "string",
                                "sourceColumn": "Customer name"
                            },
                            {
                                "name": "Reason code",
                                "dataType": "string",
                                "sourceColumn": "Reason code"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBISalesOnHold = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBISalesOnHold\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBISalesOnHold1 = CustCollectionsBIMeasurements_CustCollectionsBISalesOnHold{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBISalesOnHold\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBISalesOnHold1,[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Renamed Columns\" = Table.RenameColumns(#\"Promoted Headers\",{{\"CUSTACCOUNT\", \"Customer account\"}, {\"DATAAREAID\", \"Company\"}, {\"SALESID\", \"Sales ID\"}, {\"MCRREASONCODE\", \"Reason code\"}, {\"SALESNAME\", \"Customer name\"}})",
                                        "in",
                                        "    #\"Renamed Columns\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Collection status",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "COLLECTIONSTATUSAMOUNTS",
                                "dataType": "double",
                                "sourceColumn": "COLLECTIONSTATUSAMOUNTS"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "DISPUTESTATUSTRANSLATED",
                                "dataType": "string",
                                "sourceColumn": "DISPUTESTATUSTRANSLATED"
                            },
                            {
                                "name": "DUEDATE",
                                "dataType": "dateTime",
                                "sourceColumn": "DUEDATE"
                            },
                            {
                                "name": "CustCollectionsBIMeasurements_CustTable_FK",
                                "dataType": "int64",
                                "sourceColumn": "CustCollectionsBIMeasurements_CustTable_FK"
                            },
                            {
                                "name": "Company",
                                "dataType": "string",
                                "sourceColumn": "Company"
                            },
                            {
                                "name": "Customer account",
                                "dataType": "string",
                                "sourceColumn": "Customer account"
                            },
                            {
                                "name": "Customer name",
                                "dataType": "string",
                                "sourceColumn": "Customer name"
                            },
                            {
                                "name": "Transaction date",
                                "dataType": "dateTime",
                                "sourceColumn": "Transaction date"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBICollectionStatus = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBICollectionStatus\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBICollectionStatus1 = CustCollectionsBIMeasurements_CustCollectionsBICollectionStatus{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBICollectionStatus\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBICollectionStatus1,[Delimiter=\",\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"COLLECTIONSTATUSAMOUNTS\", type number}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"ACCOUNTNUM\", type text}, {\"CUSTOMERNAME\", type text}, {\"DISPUTESTATUSTRANSLATED\", type text}, {\"DUEDATE\", type datetime}, {\"TRANSDATE\", type datetime}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}}),",
                                        "    #\"Renamed Columns\" = Table.RenameColumns( #\"Changed Type\",{{\"ACCOUNTNUM\", \"Customer account\"}, {\"DATAAREAID\", \"Company\"}, {\"TRANSDATE\", \"Transaction date\"}, {\"CUSTOMERNAME\", \"Customer name\"}})",
                                        "in",
                                        "     #\"Renamed Columns\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Write-off",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "WRITEOFFAMOUNT",
                                "dataType": "double",
                                "sourceColumn": "WRITEOFFAMOUNT"
                            },
                            {
                                "name": "DATAAREAID",
                                "dataType": "string",
                                "sourceColumn": "DATAAREAID"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "ACCOUNTNUM",
                                "dataType": "string",
                                "sourceColumn": "ACCOUNTNUM"
                            },
                            {
                                "name": "TRANSDATE",
                                "dataType": "dateTime",
                                "sourceColumn": "TRANSDATE"
                            },
                            {
                                "name": "REASON",
                                "dataType": "string",
                                "sourceColumn": "REASON"
                            },
                            {
                                "name": "CUSTOMERNAME",
                                "dataType": "string",
                                "sourceColumn": "CUSTOMERNAME"
                            },
                            {
                                "name": "WRITEOFFREASON",
                                "dataType": "string",
                                "sourceColumn": "WRITEOFFREASON"
                            },
                            {
                                "name": "REASONCOMMENT",
                                "dataType": "string",
                                "sourceColumn": "REASONCOMMENT"
                            },
                            {
                                "name": "WRITEOFFDIMENSION",
                                "dataType": "int64",
                                "sourceColumn": "WRITEOFFDIMENSION"
                            },
                            {
                                "name": "CustCollectionsBIMeasurements_CustTable_FK",
                                "dataType": "int64",
                                "sourceColumn": "CustCollectionsBIMeasurements_CustTable_FK"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIWriteOff = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIWriteOff\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIWriteOff1 = CustCollectionsBIMeasurements_CustCollectionsBIWriteOff{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIWriteOff\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBIWriteOff1,[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"WRITEOFFAMOUNT\", type number}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"ACCOUNTNUM\", type text}, {\"TRANSDATE\", type datetime}, {\"REASON\", type text}, {\"CUSTOMERNAME\", type text}, {\"WRITEOFFREASON\", type text}, {\"REASONCOMMENT\", type text}, {\"WRITEOFFDIMENSION\", Int64.Type}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}})",
                                        "in",
                                        "    #\"Changed Type\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Open interest notes",
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIInterestNotes = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIInterestNotes\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIInterestNotes1 = CustCollectionsBIMeasurements_CustCollectionsBIInterestNotes{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIInterestNotes\"]}[Content]",
                                        "in",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIInterestNotes1"
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Open cases",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "DESCRIPTION",
                                "dataType": "string",
                                "sourceColumn": "DESCRIPTION"
                            },
                            {
                                "name": "CustCollectionsBIMeasurements_CustTable_FK",
                                "dataType": "int64",
                                "sourceColumn": "CustCollectionsBIMeasurements_CustTable_FK"
                            },
                            {
                                "name": "Case ID",
                                "dataType": "int64",
                                "sourceColumn": "Case ID"
                            },
                            {
                                "name": "Company",
                                "dataType": "string",
                                "sourceColumn": "Company"
                            },
                            {
                                "name": "Account number",
                                "dataType": "string",
                                "sourceColumn": "Account number"
                            },
                            {
                                "name": "Customer name",
                                "dataType": "string",
                                "sourceColumn": "Customer name"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBICasesOpen = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBICasesOpen\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBICasesOpen1 = CustCollectionsBIMeasurements_CustCollectionsBICasesOpen{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBICasesOpen\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBICasesOpen1,[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"CASEID\", Int64.Type}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"ACCOUNTNUM\", type text}, {\"CUSTOMERNAME\", type text}, {\"DESCRIPTION\", type text}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}}),",
                                        "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"ACCOUNTNUM\", \"Account number\"}, {\"CASEID\", \"Case ID\"}, {\"CUSTOMERNAME\", \"Customer name\"}, {\"DATAAREAID\", \"Company\"}, {\"DESCRIPTION\", \"Description\"}})",
                                        "in",
                                        "    #\"Renamed Columns\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Aging",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "CustCollectionsBIMeasurements_CustTable_FK",
                                "dataType": "int64",
                                "sourceColumn": "CustCollectionsBIMeasurements_CustTable_FK"
                            },
                            {
                                "name": "Aged balances",
                                "dataType": "double",
                                "sourceColumn": "Aged balances"
                            },
                            {
                                "name": "Company",
                                "dataType": "string",
                                "sourceColumn": "Company"
                            },
                            {
                                "name": "Customer account",
                                "dataType": "string",
                                "sourceColumn": "Customer account"
                            },
                            {
                                "name": "Aging periods",
                                "dataType": "string",
                                "sourceColumn": "Aging periods"
                            },
                            {
                                "name": "Customer name",
                                "dataType": "string",
                                "sourceColumn": "Customer name"
                            },
                            {
                                "name": "Aging period definitions",
                                "dataType": "string",
                                "sourceColumn": "Aging period definitions"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIAgedBalances = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIAgedBalances\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIAgedBalances1 = CustCollectionsBIMeasurements_CustCollectionsBIAgedBalances{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIAgedBalances\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBIAgedBalances1,[Delimiter=\",\", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"AGEDBALANCES\", type number}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"ACCOUNTNUM\", type text}, {\"HEADING\", type text}, {\"CUSTOMERNAME\", type text}, {\"AGINGNAME\", type text}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}}),",
                                        "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"ACCOUNTNUM\", \"Customer account\"}, {\"AGEDBALANCES\", \"Aged balances\"}, {\"AGINGNAME\", \"Aging period definitions\"}, {\"CUSTOMERNAME\", \"Customer name\"}, {\"DATAAREAID\", \"Company\"}, {\"HEADING\", \"Aging periods\"}})",
                                        "in",
                                        "    #\"Renamed Columns\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Collection letter amounts",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "COLLECTIONLETTERCODE_VALUE",
                                "dataType": "int64",
                                "sourceColumn": "COLLECTIONLETTERCODE_VALUE"
                            },
                            {
                                "name": "Collection letter amount",
                                "dataType": "double",
                                "sourceColumn": "Collection letter amount"
                            },
                            {
                                "name": "Company",
                                "dataType": "string",
                                "sourceColumn": "Company"
                            },
                            {
                                "name": "Transaction date",
                                "dataType": "dateTime",
                                "sourceColumn": "Transaction date"
                            },
                            {
                                "name": "Customer account",
                                "dataType": "string",
                                "sourceColumn": "Customer account"
                            },
                            {
                                "name": "Customer name",
                                "dataType": "string",
                                "sourceColumn": "Customer name"
                            },
                            {
                                "name": "Due date",
                                "dataType": "dateTime",
                                "sourceColumn": "Due date"
                            },
                            {
                                "name": "Transactions with collection letter code",
                                "dataType": "int64",
                                "sourceColumn": "Transactions with collection letter code"
                            },
                            {
                                "name": "Collection letter code",
                                "dataType": "string",
                                "sourceColumn": "Collection letter code"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBICollectionLetterAmounts = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBICollectionLetterAmounts\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBICollectionLetterAmounts1 = CustCollectionsBIMeasurements_CustCollectionsBICollectionLetterAmounts{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBICollectionLetterAmounts\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBICollectionLetterAmounts1,[Delimiter=\",\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"COLLECTIONLETTERAMOUNTS\", type number}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"TRANSDATE\", type datetime}, {\"ACCOUNTNUM\", type text}, {\"COLLECTIONLETTERCODE_VALUE\", Int64.Type}, {\"CUSTOMERNAME\", type text}, {\"DUEDATE\", type datetime}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}, {\"COLLECTIONLETTERCODE\", type text}}),",
                                        "    #\"Renamed Columns\" = Table.RenameColumns( #\"Changed Type\",{{\"ACCOUNTNUM\", \"Customer account\"}, {\"COLLECTIONLETTERAMOUNTS\", \"Collection letter amount\"}, {\"COLLECTIONLETTERCODE\", \"Collection letter code\"}, {\"CustCollectionsBIMeasurements_CustTable_FK\", \"Transactions with collection letter code\"}, {\"CUSTOMERNAME\", \"Customer name\"}, {\"DATAAREAID\", \"Company\"}, {\"DUEDATE\", \"Due date\"}, {\"TRANSDATE\", \"Transaction date\"}})",
                                        "in",
                                        "    #\"Renamed Columns\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Expected payments",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "COMPANY",
                                "dataType": "string",
                                "sourceColumn": "COMPANY"
                            },
                            {
                                "name": "DATAAREAID",
                                "dataType": "string",
                                "sourceColumn": "DATAAREAID"
                            },
                            {
                                "name": "CustCollectionsBIMeasurements_CustTable_FK",
                                "dataType": "int64",
                                "sourceColumn": "CustCollectionsBIMeasurements_CustTable_FK"
                            },
                            {
                                "name": "Expected payment amount",
                                "dataType": "double",
                                "sourceColumn": "Expected payment amount"
                            },
                            {
                                "name": "Expected payment date",
                                "dataType": "dateTime",
                                "sourceColumn": "Expected payment date"
                            },
                            {
                                "name": "Customer account",
                                "dataType": "string",
                                "sourceColumn": "Customer account"
                            },
                            {
                                "name": "Customer name",
                                "dataType": "string",
                                "sourceColumn": "Customer name"
                            },
                            {
                                "name": "Invoice number",
                                "dataType": "string",
                                "sourceColumn": "Invoice number"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIExpectedPayment = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIExpectedPayment\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIExpectedPayment1 = CustCollectionsBIMeasurements_CustCollectionsBIExpectedPayment{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIExpectedPayment\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBIExpectedPayment1,[Delimiter=\",\", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"EXPECTEDPAYMENT\", type number}, {\"COMPANY\", type text}, {\"EXPECTEDPAYDATE\", type datetime}, {\"ACCOUNTNUM\", type text}, {\"DATAAREAID\", type text}, {\"CUSTOMERNAME\", type text}, {\"INVOICE\", type text}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}}),",
                                        "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"ACCOUNTNUM\", \"Customer account\"}, {\"COMPANY\", \"Company\"}, {\"CUSTOMERNAME\", \"Customer name\"}, {\"EXPECTEDPAYDATE\", \"Expected payment date\"}, {\"EXPECTEDPAYMENT\", \"Expected payment amount\"}, {\"INVOICE\", \"Invoice number\"}})",
                                        "in",
                                        "    #\"Renamed Columns\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Open collection letters",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "COLLECTIONLETTERCODE_VALUE",
                                "dataType": "int64",
                                "sourceColumn": "COLLECTIONLETTERCODE_VALUE"
                            },
                            {
                                "name": "CustCollectionsBIMeasurements_CustTable_FK",
                                "dataType": "int64",
                                "sourceColumn": "CustCollectionsBIMeasurements_CustTable_FK"
                            },
                            {
                                "name": "Collection letters",
                                "dataType": "int64",
                                "sourceColumn": "Collection letters"
                            },
                            {
                                "name": "Company",
                                "dataType": "string",
                                "sourceColumn": "Company"
                            },
                            {
                                "name": "Customer account",
                                "dataType": "string",
                                "sourceColumn": "Customer account"
                            },
                            {
                                "name": "Customer name",
                                "dataType": "string",
                                "sourceColumn": "Customer name"
                            },
                            {
                                "name": "Print date",
                                "dataType": "dateTime",
                                "sourceColumn": "Print date"
                            },
                            {
                                "name": "Collection letter date",
                                "dataType": "dateTime",
                                "sourceColumn": "Collection letter date"
                            },
                            {
                                "name": "Collection letter code",
                                "dataType": "string",
                                "sourceColumn": "Collection letter code"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBICollectionLetter = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBICollectionLetter\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBICollectionLetter1 = CustCollectionsBIMeasurements_CustCollectionsBICollectionLetter{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBICollectionLetter\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBICollectionLetter1,[Delimiter=\",\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"COLLECTIONLETTERNUM\", Int64.Type}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"ACCOUNTNUM\", type text}, {\"CUSTOMERNAME\", type text}, {\"PRINTDATE\", type datetime}, {\"COLLECTIONLETTERDATE\", type datetime}, {\"COLLECTIONLETTERCODE_VALUE\", Int64.Type}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}, {\"COLLECTIONLETTERCODE\", type text}}),",
                                        "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"ACCOUNTNUM\", \"Customer account\"}, {\"COLLECTIONLETTERNUM\", \"Collection letters\"}, {\"COLLECTIONLETTERCODE\", \"Collection letter code\"}, {\"COLLECTIONLETTERDATE\", \"Collection letter date\"}, {\"CUSTOMERNAME\", \"Customer name\"}, {\"PRINTDATE\", \"Print date\"}, {\"DATAAREAID\", \"Company\"}})",
                                        "in",
                                        "    #\"Renamed Columns\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Balance due",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "Balance due",
                                "dataType": "double",
                                "sourceColumn": "Balance due"
                            },
                            {
                                "name": "Company",
                                "dataType": "string",
                                "sourceColumn": "Company"
                            },
                            {
                                "name": "Due date",
                                "dataType": "dateTime",
                                "sourceColumn": "Due date"
                            },
                            {
                                "name": "Customer account",
                                "dataType": "string",
                                "sourceColumn": "Customer account"
                            },
                            {
                                "name": "Customer name",
                                "dataType": "string",
                                "sourceColumn": "Customer name"
                            },
                            {
                                "name": "Key",
                                "dataType": "int64",
                                "sourceColumn": "Key"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIBalancesDue = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIBalancesDue\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIBalancesDue1 = CustCollectionsBIMeasurements_CustCollectionsBIBalancesDue{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIBalancesDue\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBIBalancesDue1,[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"SYSTEMCURRENCYAMOUNT\", type number}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"DUEDATE\", type datetime}, {\"ACCOUNTNUM\", type text}, {\"CUSTOMERNAME\", type text}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}}),",
                                        "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"ACCOUNTNUM\", \"Customer account\"}, {\"CUSTOMERNAME\", \"Customer name\"}, {\"DATAAREAID\", \"Company\"}, {\"DUEDATE\", \"Due date\"}, {\"SYSTEMCURRENCYAMOUNT\", \"Balance due\"}, {\"CustCollectionsBIMeasurements_CustTable_FK\", \"Key\"}})",
                                        "in",
                                        "    #\"Renamed Columns\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "30 days sales outstanding",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "DSO30",
                                "dataType": "int64",
                                "sourceColumn": "DSO30"
                            },
                            {
                                "name": "DATAAREAID",
                                "dataType": "string",
                                "sourceColumn": "DATAAREAID"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "ACCOUNTNUM",
                                "dataType": "string",
                                "sourceColumn": "ACCOUNTNUM"
                            },
                            {
                                "name": "CUSTOMERNAME",
                                "dataType": "string",
                                "sourceColumn": "CUSTOMERNAME"
                            },
                            {
                                "name": "CustCollectionsBIMeasurements_CustTable_FK",
                                "dataType": "int64",
                                "sourceColumn": "CustCollectionsBIMeasurements_CustTable_FK"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "CustCollectionsBIMeasurements_CustCollectionsBIDSO30 = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIDSO30\"]}[Content],",
                                        "CustCollectionsBIMeasurements_CustCollectionsBIDSO1 = CustCollectionsBIMeasurements_CustCollectionsBIDSO30{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIDSO30\"]}[Content],",
                                        "#\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBIDSO1,[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "#\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "#\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"DSO30\", Int64.Type}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"ACCOUNTNUM\", type text}, {\"CUSTOMERNAME\", type text}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}})",
                                        "in",
                                        "#\"Changed Type\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Customers over credit limit",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "Amount over credit limit",
                                "dataType": "double",
                                "sourceColumn": "Amount over credit limit"
                            },
                            {
                                "name": "Company",
                                "dataType": "string",
                                "sourceColumn": "Company"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "Customer account",
                                "dataType": "string",
                                "sourceColumn": "Customer account"
                            },
                            {
                                "name": "Customer name",
                                "dataType": "string",
                                "sourceColumn": "Customer name"
                            },
                            {
                                "name": "Credit remaining",
                                "dataType": "double",
                                "sourceColumn": "Credit remaining"
                            },
                            {
                                "name": "Credit limit",
                                "dataType": "double",
                                "sourceColumn": "Credit limit"
                            },
                            {
                                "name": "Credit rating",
                                "dataType": "string",
                                "sourceColumn": "Credit rating"
                            },
                            {
                                "name": "CustCollectionsBIMeasurements_CustTable_FK",
                                "dataType": "int64",
                                "sourceColumn": "CustCollectionsBIMeasurements_CustTable_FK"
                            },
                            {
                                "name": "Balance",
                                "dataType": "double",
                                "sourceColumn": "Balance"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBICredit = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBICredit\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBICredit1 = CustCollectionsBIMeasurements_CustCollectionsBICredit{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBICredit\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBICredit1,[Delimiter=\",\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"AMOUNTOVERCREDITLIMIT\", type number}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"ACCOUNTNUM\", type text}, {\"CUSTOMERNAME\", type text}, {\"CREDITREMAINING\", type number}, {\"SYSTEMCURRENCYCREDITMAX\", type number}, {\"CREDITRATING\", type text}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}, {\"CREDITEXPOSED\", type number}}),",
                                        "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each [AMOUNTOVERCREDITLIMIT] > 0),",
                                        "    #\"Filtered Rows1\" = Table.SelectRows(#\"Filtered Rows\", each [SYSTEMCURRENCYCREDITMAX] > 0),",
                                        "    #\"Renamed Columns\" = Table.RenameColumns(#\"Filtered Rows1\",{{\"CREDITEXPOSED\", \"Balance\"}, {\"SYSTEMCURRENCYCREDITMAX\", \"Credit limit\"}, {\"AMOUNTOVERCREDITLIMIT\", \"Amount over credit limit\"}, {\"ACCOUNTNUM\", \"Customer account\"}, {\"CUSTOMERNAME\", \"Customer name\"}, {\"DATAAREAID\", \"Company\"}, {\"CREDITRATING\", \"Credit rating\"}, {\"CREDITREMAINING\", \"Credit remaining\"}})",
                                        "in",
                                        "     #\"Renamed Columns\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Customers on credit",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "Amount over credit limit",
                                "dataType": "double",
                                "sourceColumn": "Amount over credit limit"
                            },
                            {
                                "name": "Company",
                                "dataType": "string",
                                "sourceColumn": "Company"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "Customer account",
                                "dataType": "string",
                                "sourceColumn": "Customer account"
                            },
                            {
                                "name": "Customer name",
                                "dataType": "string",
                                "sourceColumn": "Customer name"
                            },
                            {
                                "name": "Credit remaining",
                                "dataType": "double",
                                "sourceColumn": "Credit remaining"
                            },
                            {
                                "name": "Credit limit",
                                "dataType": "double",
                                "sourceColumn": "Credit limit"
                            },
                            {
                                "name": "Credit rating",
                                "dataType": "string",
                                "sourceColumn": "Credit rating"
                            },
                            {
                                "name": "CustCollectionsBIMeasurements_CustTable_FK",
                                "dataType": "int64",
                                "sourceColumn": "CustCollectionsBIMeasurements_CustTable_FK"
                            },
                            {
                                "name": "Balance",
                                "dataType": "double",
                                "sourceColumn": "Balance"
                            },
                            {
                                "name": "Percentage of credit remaining",
                                "dataType": "double",
                                "sourceColumn": "Percentage of credit remaining"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBICredit = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBICredit\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBICredit1 = CustCollectionsBIMeasurements_CustCollectionsBICredit{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBICredit\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBICredit1,[Delimiter=\",\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"AMOUNTOVERCREDITLIMIT\", type number}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"ACCOUNTNUM\", type text}, {\"CUSTOMERNAME\", type text}, {\"CREDITREMAINING\", type number}, {\"SYSTEMCURRENCYCREDITMAX\", type number}, {\"CREDITRATING\", type text}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}, {\"CREDITEXPOSED\", type number}}),",
                                        "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each [SYSTEMCURRENCYCREDITMAX] > 0),",
                                        "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Percentage of credit remaining\", each [CREDITREMAINING]/[SYSTEMCURRENCYCREDITMAX]*100),",
                                        "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Percentage of credit remaining\", type number}}),",
                                        "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"SYSTEMCURRENCYCREDITMAX\", \"Credit limit\"}, {\"AMOUNTOVERCREDITLIMIT\", \"Amount over credit limit\"}, {\"ACCOUNTNUM\", \"Customer account\"}, {\"CREDITEXPOSED\", \"Balance\"}, {\"CREDITRATING\", \"Credit rating\"}, {\"CREDITREMAINING\", \"Credit remaining\"}, {\"CUSTOMERNAME\", \"Customer name\"}, {\"DATAAREAID\", \"Company\"}})",
                                        "in",
                                        "    #\"Renamed Columns\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Open activities",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "CATEGORY_VALUE",
                                "dataType": "int64",
                                "sourceColumn": "CATEGORY_VALUE"
                            },
                            {
                                "name": "CustCollectionsBIMeasurements_CustTable_FK",
                                "dataType": "int64",
                                "sourceColumn": "CustCollectionsBIMeasurements_CustTable_FK"
                            },
                            {
                                "name": "Activity number",
                                "dataType": "int64",
                                "sourceColumn": "Activity number"
                            },
                            {
                                "name": "Company",
                                "dataType": "string",
                                "sourceColumn": "Company"
                            },
                            {
                                "name": "Customer account",
                                "dataType": "string",
                                "sourceColumn": "Customer account"
                            },
                            {
                                "name": "Customer name",
                                "dataType": "string",
                                "sourceColumn": "Customer name"
                            },
                            {
                                "name": "Purpose",
                                "dataType": "string",
                                "sourceColumn": "Purpose"
                            },
                            {
                                "name": "Type",
                                "dataType": "string",
                                "sourceColumn": "Type"
                            },
                            {
                                "name": "Start date",
                                "dataType": "dateTime",
                                "sourceColumn": "Start date"
                            },
                            {
                                "name": "End date",
                                "dataType": "dateTime",
                                "sourceColumn": "End date"
                            },
                            {
                                "name": "Category",
                                "dataType": "string",
                                "sourceColumn": "Category"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIActivitiesOpen = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIActivitiesOpen\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBIActivitiesOpen1 = CustCollectionsBIMeasurements_CustCollectionsBIActivitiesOpen{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBIActivitiesOpen\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBIActivitiesOpen1,[Delimiter=\",\", Columns=14, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"ACTIVITYNUMBER\", Int64.Type}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"ACCOUNTNUM\", type text}, {\"CUSTOMERNAME\", type text}, {\"CATEGORY_VALUE\", Int64.Type}, {\"PURPOSE\", type text}, {\"TYPEID\", type text}, {\"STARTDATETIME\", type datetime}, {\"ENDDATETIME\", type datetime}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}, {\"CATEGORY\", type text}}),",
                                        "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"ACCOUNTNUM\", \"Customer account\"}, {\"ACTIVITYNUMBER\", \"Activity number\"}, {\"DATAAREAID\", \"Company\"}, {\"CATEGORY\", \"Category\"}, {\"CUSTOMERNAME\", \"Customer name\"}, {\"ENDDATETIME\", \"End date\"}, {\"PURPOSE\", \"Purpose\"}, {\"STARTDATETIME\", \"Start date\"}, {\"TYPEID\", \"Type\"}})",
                                        "in",
                                        "    #\"Renamed Columns\""
                                    ]
                                }
                            }
                        ]
                    },
                    {
                        "name": "Case average closed time",
                        "columns": [
                            {
                                "name": "@odata.etag",
                                "dataType": "string",
                                "sourceColumn": "@odata.etag"
                            },
                            {
                                "name": "ItemInternalId",
                                "dataType": "string",
                                "sourceColumn": "ItemInternalId"
                            },
                            {
                                "name": "PARTITION",
                                "dataType": "double",
                                "sourceColumn": "PARTITION"
                            },
                            {
                                "name": "CustCollectionsBIMeasurements_CustTable_FK",
                                "dataType": "int64",
                                "sourceColumn": "CustCollectionsBIMeasurements_CustTable_FK"
                            },
                            {
                                "name": "Average days close",
                                "dataType": "int64",
                                "sourceColumn": "Average days close"
                            },
                            {
                                "name": "Case ID",
                                "dataType": "int64",
                                "sourceColumn": "Case ID"
                            },
                            {
                                "name": "Company",
                                "dataType": "string",
                                "sourceColumn": "Company"
                            },
                            {
                                "name": "Customer account",
                                "dataType": "string",
                                "sourceColumn": "Customer account"
                            },
                            {
                                "name": "Customer name",
                                "dataType": "string",
                                "sourceColumn": "Customer name"
                            }
                        ],
                        "partitions": [
                            {
                                "name": "Partition",
                                "dataView": "full",
                                "source": {
                                    "type": "m",
                                    "expression": [
                                        "let",
                                        "    Source=#\"dataLakeStore\",",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBICaseAverageCloseTime = Source{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBICaseAverageCloseTime\"]}[Content],",
                                        "    CustCollectionsBIMeasurements_CustCollectionsBICaseAverageCloseTime1 = CustCollectionsBIMeasurements_CustCollectionsBICaseAverageCloseTime{[Name=\"CustCollectionsBIMeasurements_CustCollectionsBICaseAverageCloseTime\"]}[Content],",
                                        "    #\"Imported CSV\" = Csv.Document(CustCollectionsBIMeasurements_CustCollectionsBICaseAverageCloseTime1,[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                                        "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                                        "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"@odata.etag\", type text}, {\"ItemInternalId\", type text}, {\"CASEAVERAGECLOSEDTIME\", Int64.Type}, {\"NUMOFCASES\", Int64.Type}, {\"DATAAREAID\", type text}, {\"PARTITION\", type number}, {\"ACCOUNTNUM\", type text}, {\"CUSTOMERNAME\", type text}, {\"CustCollectionsBIMeasurements_CustTable_FK\", Int64.Type}}),",
                                        "    #\"Renamed Columns\" = Table.RenameColumns( #\"Changed Type\",{{\"ACCOUNTNUM\", \"Customer account\"}, {\"CASEAVERAGECLOSEDTIME\", \"Average days close\"}, {\"DATAAREAID\", \"Company\"}, {\"CUSTOMERNAME\", \"Customer name\"}, {\"NUMOFCASES\", \"Case ID\"}})",
                                        "in",
                                        "    #\"Renamed Columns\""
                                    ]
                                }
                            }
                        ]
                    }
                ],
                "relationships": [
                    {
                        "name": "5e416790-923d-4dde-8c53-8cc08b5a2aaf",
                        "fromTable": "Open activities",
                        "fromColumn": "CustCollectionsBIMeasurements_CustTable_FK",
                        "toTable": "Customer dimension",
                        "toColumn": "ROW_UNIQUEKEY"
                    },
                    {
                        "name": "f06ccec8-e173-4672-b818-5b5e17f233ce",
                        "fromTable": "Open collection letters",
                        "fromColumn": "CustCollectionsBIMeasurements_CustTable_FK",
                        "toTable": "Customer dimension",
                        "toColumn": "ROW_UNIQUEKEY"
                    },
                    {
                        "name": "e057ac93-dc9a-4c49-9bcd-691f1ff2e9f7",
                        "fromTable": "Aging",
                        "fromColumn": "CustCollectionsBIMeasurements_CustTable_FK",
                        "toTable": "Customer dimension",
                        "toColumn": "ROW_UNIQUEKEY",
                        "crossFilteringBehavior": "bothDirections"
                    },
                    {
                        "name": "20922433-40fe-4e93-9b44-e02c2648af22",
                        "fromTable": "Case average closed time",
                        "fromColumn": "CustCollectionsBIMeasurements_CustTable_FK",
                        "toTable": "Customer dimension",
                        "toColumn": "ROW_UNIQUEKEY"
                    },
                    {
                        "name": "0a91e4e2-5a0f-4347-8920-3762c9b16bc6",
                        "fromTable": "Expected payments",
                        "fromColumn": "COMPANY",
                        "toTable": "Customer dimension",
                        "toColumn": "ROW_UNIQUEKEY",
                        "crossFilteringBehavior": "bothDirections"
                    },
                    {
                        "name": "82e96357-c94c-4365-97ce-4f3600850684",
                        "fromTable": "Write-off",
                        "fromColumn": "CustCollectionsBIMeasurements_CustTable_FK",
                        "toTable": "Customer dimension",
                        "toColumn": "ROW_UNIQUEKEY",
                        "crossFilteringBehavior": "bothDirections"
                    },
                    {
                        "name": "a467eb32-fa79-4c04-9631-f4843595d030",
                        "fromTable": "Open cases",
                        "fromColumn": "CustCollectionsBIMeasurements_CustTable_FK",
                        "toTable": "Customer dimension",
                        "toColumn": "ROW_UNIQUEKEY"
                    },
                    {
                        "name": "c8df1c3e-e3a0-4470-a599-12b8b6382f9d",
                        "fromTable": "30 days sales outstanding",
                        "fromColumn": "CustCollectionsBIMeasurements_CustTable_FK",
                        "toTable": "Customer dimension",
                        "toColumn": "ROW_UNIQUEKEY"
                    },
                    {
                        "name": "cc44d6e6-f1a5-41e2-a5bf-a5706b1962f5",
                        "fromTable": "Collection status",
                        "fromColumn": "CustCollectionsBIMeasurements_CustTable_FK",
                        "toTable": "Customer dimension",
                        "toColumn": "ROW_UNIQUEKEY",
                        "crossFilteringBehavior": "bothDirections"
                    },
                    {
                        "name": "7d4f308c-d128-41d7-b238-4886fcad0649",
                        "fromTable": "Sales on hold",
                        "fromColumn": "CustCollectionsBIMeasurements_CustTable_FK",
                        "toTable": "Customer dimension",
                        "toColumn": "ROW_UNIQUEKEY"
                    },
                    {
                        "name": "9d3b7cf5-b227-4947-9d24-b3b251a4491d",
                        "fromTable": "Customers on hold",
                        "fromColumn": "CustCollectionsBIMeasurements_CustTable_FK",
                        "toTable": "Customer dimension",
                        "toColumn": "ROW_UNIQUEKEY"
                    },
                    {
                        "name": "5df808e7-ac30-4976-a271-0a80207bc7a3",
                        "fromTable": "Customers over credit limit",
                        "fromColumn": "CustCollectionsBIMeasurements_CustTable_FK",
                        "toTable": "Customer dimension",
                        "toColumn": "ROW_UNIQUEKEY",
                        "crossFilteringBehavior": "bothDirections"
                    },
                    {
                        "name": "9886cf2c-ba75-4041-8528-c73759713b5e",
                        "fromTable": "Customers on credit",
                        "fromColumn": "CustCollectionsBIMeasurements_CustTable_FK",
                        "toTable": "Customer dimension",
                        "toColumn": "ROW_UNIQUEKEY",
                        "crossFilteringBehavior": "bothDirections"
                    }
                ],
                "annotations": [
                    {
                        "name": "ClientCompatibilityLevel",
                        "value": "500"
                    }
                ]
            },
            "id": "CreditCollections"
        }
    }
}